# Generated by Django 5.0.14 on 2026-08-05 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('view_inventory_reports', 'Can view inventory reports'), ('view_sales_reports', 'Can view sales reports'), ('view_purchase_reports', 'Can view purchase reports'), ('view_financial_reports', 'Can view financial reports')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
