from django import forms

from .models import Supplier


class SupplierForm(forms.ModelForm):
    """supplier_code is deliberately excluded — auto-generated by
    suppliers.services.create_supplier(), never user-editable.

    QA polish (Sprint 4): "Company Name" -> "Supplier Name" (not every
    supplier is a registered company), and Country defaults to Nigeria.
    Both are form-level only — company_name is still the real field/
    column name (renaming it would need a migration, which QA explicitly
    said to avoid unless required); the model's own `country` field still
    defaults to blank, only this form's initial value nudges new entries
    toward Nigeria while leaving it fully editable.
    """

    country = forms.CharField(required=False, initial="Nigeria")

    class Meta:
        model = Supplier
        fields = [
            "company_name", "contact_person", "phone", "email",
            "address", "city", "state", "country", "status", "notes",
        ]
        labels = {
            "company_name": "Supplier Name",
        }
        widgets = {
            "address": forms.Textarea(attrs={"rows": 2}),
            "notes": forms.Textarea(attrs={"rows": 2}),
        }
